# Generated by Django 2.1.2 on 2019-06-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(max_length=1000)),
                ('audio_url', models.URLField(max_length=1000, null=True)),
                ('otrkey', models.CharField(max_length=200)),
                ('decrypted', models.CharField(max_length=200)),
                ('cutlist', models.CharField(max_length=5000, null=True)),
                ('log', models.CharField(max_length=50000)),
                ('keep', models.BooleanField(default=False)),
            ],
        ),
    ]
