# Generated by Django 2.1.2 on 2018-11-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=300)),
                ('website', models.CharField(max_length=2)),
                ('series', models.CharField(max_length=200)),
                ('german', models.BooleanField()),
                ('otrNameFormat', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
