# Generated by Django 2.1.2 on 2018-11-27 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0002_series_numepisodes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='numEpisodes',
            new_name='numSeasons',
        ),
    ]
