# Generated by Django 3.0.6 on 2020-05-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0003_auto_20181127_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
